#!/usr/bin/env python3
"""Write (or --check) the expected SULO target graphs and negative outcomes.

One directory per Agent 2 fixture, mirroring ``fixtures/r4/``.  Each holds:

    outcome.json   the declared outcome of running the map on that fixture,
                   cross-checked against Agent 2's own declaration in
                   ``fixtures/r4/<family>/<id>/case.json``
    target.nt      the expected SULO graph, sorted N-Triples -- only for the
                   fixtures the map materializes

``--check`` re-runs the maps and fails on any drift, exactly like Agent 2's
``fixtures/r4/build.py``.  ``tests/contracts/maps/test_expected_graphs.py``
runs it.

These files are generated and then reviewed; they are regression evidence.
They are NOT the acceptance conditions.  Those are hand-written invariants in
``tests/contracts/maps/test_egfr_gate2.py`` and ``test_bp_gate3.py`` which do
not read these files, so a wrong graph regenerated here still fails there.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO / "src"))
sys.path.insert(0, str(REPO / "tests/contracts"))

import os
os.environ.setdefault("FHIR_SULO_POLICY_DIR", str(REPO / "policies"))

from maps import bp_case, egfr_case, encounter_case  # noqa: E402
from maps._engine import mapjob  # noqa: E402

HERE = Path(__file__).resolve().parent
QUALITY_MODE = "per-observation"

BANNER = (
    "# Generated by fixtures/expected/build.py. Do not hand-edit; run the script.\n"
    "# Expected SULO target graph, canonical sorted N-Triples.\n"
)


def declared(family: str, fixture_id: str) -> str:
    case = json.loads((REPO / "fixtures/r4" / family / fixture_id / "case.json").read_text())
    return case["expected"]["eligibility"]


def failure_summary(validation):
    """The element paths a ShEx Failure blames, as stable evidence."""
    preds, kinds = set(), set()

    def walk(n):
        if isinstance(n, dict):
            t = n.get("triple")
            if isinstance(t, dict) and t.get("predicate"):
                preds.add(t["predicate"].rsplit("/", 1)[-1])
            if isinstance(n.get("type"), str) and n["type"].endswith(("Violation", "Mismatch")):
                kinds.add(n["type"])
            for v in n.values():
                walk(v)
        elif isinstance(n, list):
            for v in n:
                walk(v)

    walk(validation.get("failure"))
    return {"violations": sorted(kinds), "elements": sorted(preds)}


def outcome_for(result, family, fixture_id, map_id, extra=None):
    d = declared(family, fixture_id)
    if result["stage"] == "validate":
        map_outcome, diagnostic = "source-shape-nonconformant", failure_summary(result["validation"])
    elif result["stage"] == "identity":
        map_outcome, diagnostic = "identity-rejected", result["identityRejection"]
    elif result["ok"]:
        map_outcome, diagnostic = "mapped", None
    else:
        map_outcome, diagnostic = "materialization-error", [
            p["error"] for p in result["passes"] if p["error"]
        ]

    doc = {
        "format": "fhir-sulo/expected-target/0.1.0",
        "fixture_id": fixture_id,
        "family": family,
        "map_id": map_id,
        "declared_by_agent2": d,
        "map_outcome": map_outcome,
        "agrees_with_agent2": (map_outcome == "mapped") == (d == "eligible"),
        "diagnostic": diagnostic,
        "run_parameters": {
            "quality_identity_mode": QUALITY_MODE,
            "quality_identity_mode_note":
                "Review item R2 is unanswered and the shipped default rejects every "
                "request. The mode is set explicitly here so a graph exists at all; "
                "answering R2 moves every quality IRI in target.nt and nothing else.",
            "sulo_version": "0.2.12",
            "engine": "shex@1.0.0-alpha.33 via ThreadedMaterializer",
        },
        "target_graph": "target.nt" if map_outcome == "mapped" else None,
    }
    if extra:
        doc.update(extra)
    return doc


def write(path: Path, text: str, check: bool, drift: list) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if check:
        if not path.exists():
            drift.append("missing: %s" % path.relative_to(REPO))
        elif path.read_text() != text:
            drift.append("drift: %s" % path.relative_to(REPO))
    else:
        path.write_text(text)


def graph_text(nquads: str) -> str:
    lines = sorted(set(l for l in nquads.splitlines() if l.strip()))
    return BANNER + "\n".join(lines) + "\n"


def main(check: bool) -> int:
    drift: list = []

    # ---- eGFR -------------------------------------------------------------
    for d in sorted((REPO / "fixtures/r4/egfr").iterdir()):
        if not d.is_dir():
            continue
        fid = d.name
        result = egfr_case.run(fid, quality_mode=QUALITY_MODE)
        out = HERE / "egfr" / fid
        doc = outcome_for(result, "egfr", fid, "fhir-r4-egfr-solid")
        if doc["map_outcome"] == "mapped":
            doc["triple_count"] = len([l for l in result["nquads"].splitlines() if l])
            write(out / "target.nt", graph_text(result["nquads"]), check, drift)
        write(out / "outcome.json", json.dumps(doc, indent=2) + "\n", check, drift)

    # ---- blood pressure ---------------------------------------------------
    for d in sorted((REPO / "fixtures/r4/bp").iterdir()):
        if not d.is_dir():
            continue
        fid = d.name
        rdf, ids = bp_case.resources(fid)
        results = {o: bp_case.run(fid, o, rdf=rdf, quality_mode=QUALITY_MODE) for o in ids}
        out = HERE / "bp" / fid
        combined = "\n".join(r["nquads"] for r in results.values())
        first = next(iter(results.values()))
        doc = outcome_for(first, "bp", fid, "fhir-r4-bp-panel-solid", extra={
            "resources": ids,
            "panel_tuples": sorted(
                bp_case.binding_tree(fid, results).tuples_for_scope(
                    "panel", ["panel", "sys", "dia"])),
        })
        doc["panel_tuples"] = [list(t) for t in doc["panel_tuples"]]
        if doc["map_outcome"] == "mapped":
            doc["triple_count"] = len(set(l for l in combined.splitlines() if l))
            write(out / "target.nt", graph_text(combined), check, drift)
        write(out / "outcome.json", json.dumps(doc, indent=2) + "\n", check, drift)

    # ---- Encounter --------------------------------------------------------
    for d in sorted((REPO / "fixtures/r4/encounter").iterdir()):
        if not d.is_dir():
            continue
        fid = d.name
        result = encounter_case.run(fid)
        out = HERE / "encounter" / fid
        doc = outcome_for(result, "encounter", fid, "fhir-r4-encounter-pro")
        if doc["map_outcome"] == "mapped":
            doc["triple_count"] = len([l for l in result["nquads"].splitlines() if l])
            write(out / "target.nt", graph_text(result["nquads"]), check, drift)
        write(out / "outcome.json", json.dumps(doc, indent=2) + "\n", check, drift)

    if check and drift:
        for line in drift:
            print(line)
        return 1
    print("ok" if check else "written")
    return 0


if __name__ == "__main__":
    raise SystemExit(main("--check" in sys.argv))
