#!/usr/bin/env python3
"""Regenerate the derived RDF artifacts under ``fixtures/r4/``.

Hand-authored, never generated:  ``*.json`` sources, ``case.json``,
                                 ``expected-bindings.json``
Generated here:                  ``canonical.nt``, ``readable.ttl``, and the
                                 named variants a ``case.json`` declares.

Run with ``--check`` in CI to assert the committed artifacts match what the
pinned renderer produces right now. A drift is a renderer change and must be a
reviewed commit, not a silent regeneration.

Usage:
    python3 fixtures/r4/build.py            # write
    python3 fixtures/r4/build.py --check    # verify, exit 1 on drift
"""

from __future__ import annotations

import argparse
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
sys.path.insert(0, os.path.join(ROOT, "src"))

from fhir_sulo.ingest import jsonio, render  # noqa: E402
from fhir_sulo.ingest import turtle  # noqa: E402
from fhir_sulo.ingest.ntriples import serialize  # noqa: E402

BANNER = (
    "# Generated by fixtures/r4/build.py from the sources in this directory.\n"
    "# Canonical form: sorted N-Triples. Do not hand-edit; run the script.\n"
)


def iter_cases():
    for family in sorted(os.listdir(HERE)):
        fdir = os.path.join(HERE, family)
        if not os.path.isdir(fdir):
            continue
        for name in sorted(os.listdir(fdir)):
            cdir = os.path.join(fdir, name)
            cpath = os.path.join(cdir, "case.json")
            if os.path.isfile(cpath):
                with open(cpath, encoding="utf-8") as fh:
                    yield cdir, json.load(fh)


def render_sources(case_dir, sources):
    triples, roots = [], []
    for src in sources:
        with open(os.path.join(case_dir, src), encoding="utf-8") as fh:
            resource = jsonio.loads(fh.read())
        r = render(resource)
        # Re-label blank nodes per source so a multi-resource fixture cannot
        # accidentally share one.
        prefix = os.path.splitext(src)[0].replace(".", "_")
        triples.extend(_relabel(r.triples, prefix))
        roots.append(r.root)
    return triples, roots


def _relabel(triples, prefix):
    from fhir_sulo.ingest.ntriples import BNode, Triple

    def fix(t):
        return BNode(f"{prefix}-{t.label}") if isinstance(t, BNode) else t

    return [Triple(fix(t.s), t.p, fix(t.o)) for t in triples]


def reorder(nt_text: str) -> str:
    """A deterministic non-sorted permutation of the same lines.

    Reverses the canonical order and interleaves halves, so the result is
    demonstrably a different serialisation of an identical triple set.
    """
    lines = [l for l in nt_text.splitlines() if l and not l.startswith("#")]
    rev = list(reversed(lines))
    half = (len(rev) + 1) // 2
    a, b = rev[:half], rev[half:]
    out = []
    for i in range(half):
        out.append(a[i])
        if i < len(b):
            out.append(b[i])
    assert sorted(out) == sorted(lines)
    return "\n".join(out) + "\n"


def emit(path, text, check, drifted):
    body = BANNER + text
    if check:
        existing = open(path, encoding="utf-8").read() if os.path.exists(path) else None
        if existing != body:
            drifted.append(os.path.relpath(path, ROOT))
        return
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(body)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    drifted: list = []
    n = 0

    for case_dir, case in iter_cases():
        triples, roots = render_sources(case_dir, case["sources"])
        nt = serialize(triples)
        emit(os.path.join(case_dir, "canonical.nt"), nt, args.check, drifted)
        emit(os.path.join(case_dir, "readable.ttl"),
             turtle.serialize(triples, root=roots[0] if len(roots) == 1 else None),
             args.check, drifted)
        n += 1

        for vname, v in (case.get("variants") or {}).items():
            if "sources" in v:
                vt, _ = render_sources(case_dir, v["sources"])
                emit(os.path.join(case_dir, v["rdf"]), serialize(vt), args.check, drifted)
            else:
                emit(os.path.join(case_dir, v["rdf"]), reorder(nt), args.check, drifted)

    if args.check:
        if drifted:
            print("DRIFT: committed fixture RDF does not match the pinned renderer:")
            for p in drifted:
                print("  " + p)
            return 1
        print(f"OK: {n} fixture cases match the pinned renderer")
        return 0
    print(f"wrote RDF for {n} fixture cases")
    return 0


if __name__ == "__main__":
    sys.exit(main())
